[package]
name = "doodle-piston-tut"
version = "0.1.0"
authors = ["meidhy <dymayday@gmail.com>"]

[dependencies]
piston = "*"
piston2d-graphics = "*"
pistoncore-glutin_window = "*"
piston2d-opengl_graphics = "*"
fps_counter = "*"
